# Application
spring:
  application:
    name: eureka-client

server:
  port: 8081

# Log
logging:
  config: classpath:logback.xml

# Eureka
eureka:
  client:
    eureka-service-url-poll-interval-seconds: 10 #默认为300秒，这里为了验证改为10秒
    service-url:
      default-zone: http://eureka:8761/eureka
      #default-zone=http://eureka1:8761,http://eureka2:8762
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}



