# Application
spring:
  application:
    name: eureka-server

server:
  port: 8761

# Eureka配置
eureka:
  client:
    service-url:
      default-zone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Log
logging:
  config: classpath:logback.xml

