# Application
spring:
  application:
    name: service-provider

server:
  port: 8081

# Log
logging:
  config: classpath:logback.xml

# Eureka配置
eureka:
  client:
    service-url:
      default-zone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true