# Application
spring:
  application:
    name: service-provider

server:
  port: ${port}

# Log
logging:
  config: classpath:logback.xml

# Eureka配置
eureka:
  instance:
    metadata-map:
      group: service-provider-group
      version: 1.0
      region: ${env}
  client:
    service-url:
      default-zone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true
