# Application
spring:
  application:
    name: message-consumer
  rabbitmq:
    username: admin
    password: admin
    host: eureka
    port: 5672
  cloud:
    stream:
      bindings:
        myInput:
          destination: minestream
          group: stream
        myOutput:
          destination: minestream

server:
  port: ${port:8091}

# Log
logging:
  config: classpath:logback.xml

# Eureka配置
eureka:
  client:
    service-url:
      default-zone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true
